### PR TITLE
Replace url of Star Wars API

### PR DESCRIPTION
**Pull request by LuRsT**
The url for the SWAPI has changed from `swapi.co` to `swapi.dev`

[More here](https://swapi.dev/about)

### CODE REVIEW

**Comment by sonylnagale** [comment]
@LuRsT has this propagated? The cert is invalid and bypassing that with Chromium just says "Unknown app".

**Comment by LuRsT** [comment]
@sonylnagale, yeah, it has propagated, at least on my end, `swapi.co` doesn't even exist anymore and `swapi.dev` seems to have the right certificates. I get unknown app with `swapi.co`.

**Comment by sonylnagale** [comment]
@LuRsT interesting—on my end I see that `Puma-dev CA is not trusted` and Chrome refuses to display.

**Comment by LuRsT** [comment]
Odd, could it be your DNS supplier? The certificate is from Let's Encrypt. Here is the screenshot of the about page from swapi:

2020-05-28-182557_1268x506_scrot

**Comment by sonylnagale** [comment]
@LuRsT it seems that macOS doesn't trust the Puma-Dev cert (at least, not by [default](https://github.com/puma/puma-dev/issues/84)) so I suppose the only option would be to file an issue. I'll do that and thank you very much for pointing this out.

**Comment by sonylnagale** [comment]
@LuRsT I finally  figured out the problem: I had a DNS issue of all things, so it routed the SSL incorrectly. When I use Google's DNS servers, it's fine. I'll go ahead apply these changes after a quick check. Thanks!

**Pull request merged**
